import React, { useEffect, useState } from 'react';
import { Loader2, Save } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../lib/supabase';

type CreatorPlan={id?:string;name:string;tier:'basic'|'vip'|'exclusive';monthly_price:number;semiannual_price:number;annual_price:number;benefits:string[];is_active:boolean};
const defaults:CreatorPlan[]=[
 {name:'Básico',tier:'basic',monthly_price:29.90,semiannual_price:149.90,annual_price:299.90,benefits:['Conteúdo exclusivo'],is_active:true},
 {name:'VIP',tier:'vip',monthly_price:59.90,semiannual_price:299.90,annual_price:599.90,benefits:['Conteúdo VIP','Lives pagas'],is_active:true},
 {name:'Exclusivo',tier:'exclusive',monthly_price:99.90,semiannual_price:499.90,annual_price:999.90,benefits:['Conteúdo exclusivo','Atendimento prioritário'],is_active:true}
];
export const CreatorPlansManager:React.FC<{creatorId:string}>=({creatorId})=>{
 const [plans,setPlans]=useState<CreatorPlan[]>(defaults); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{if(!supabase||!isSupabaseConfigured||creatorId.startsWith('cr-')){setLoading(false);return;} const {data,error}=await supabase.from('subscription_plans').select('*').eq('creator_id',creatorId).order('tier'); if(error){setMessage('Execute a migração 012 para usar os planos reais.');} if(data&&data.length)setPlans(data.map((p:any)=>({id:p.id,name:p.name,tier:p.tier,monthly_price:Number(p.monthly_price??p.price??0),semiannual_price:Number(p.semiannual_price??0),annual_price:Number(p.annual_price??0),benefits:Array.isArray(p.benefits)?p.benefits:[],is_active:p.is_active!==false}))); setLoading(false);})();},[creatorId]);
 const save=async()=>{if(!supabase||!isSupabaseConfigured)return;setSaving(true);setMessage('');const rows=plans.map(p=>({...(p.id?{id:p.id}:{}),creator_id:creatorId,name:p.name,tier:p.tier,price:p.monthly_price,monthly_price:p.monthly_price,semiannual_price:p.semiannual_price,annual_price:p.annual_price,benefits:p.benefits,is_active:p.is_active}));const {error}=await supabase.from('subscription_plans').upsert(rows);setMessage(error?.message||'Planos mensal, semestral e anual salvos no Supabase.');setSaving(false);};
 if(loading)return <div className="mt-6 flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-rose-400"/></div>;
 return <section className="mt-6 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Planos de assinatura</h2><p className="mt-1 text-xs text-zinc-500">Você define os valores e benefícios de cada período.</p></div><button onClick={save} disabled={saving||!isSupabaseConfigured} className="flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2 text-xs font-bold disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Salvando...':'Salvar'}</button></div>{message&&<p className="mt-3 text-xs text-amber-300">{message}</p>}<div className="mt-5 grid gap-3 md:grid-cols-3">{plans.map((p,i)=><article key={p.id||p.tier} className="rounded-2xl border border-zinc-800 bg-zinc-950/60 p-4 space-y-2"><input value={p.name} onChange={e=>setPlans(v=>v.map((x,j)=>j===i?{...x,name:e.target.value}:x))} className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-2 text-sm font-bold"/>{(['monthly_price','semiannual_price','annual_price'] as const).map((field)=><label key={field} className="block text-xs text-zinc-500">{field==='monthly_price'?'Mensal':field==='semiannual_price'?'Semestral':'Anual'} (R$)<input type="number" min="0" step=".01" value={p[field]} onChange={e=>setPlans(v=>v.map((x,j)=>j===i?{...x,[field]:Number(e.target.value)}:x))} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-2 text-sm"/></label>)}<textarea value={p.benefits.join('\n')} onChange={e=>setPlans(v=>v.map((x,j)=>j===i?{...x,benefits:e.target.value.split('\n')}:x))} placeholder="Benefícios, um por linha" className="min-h-16 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-2 text-xs"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={p.is_active} onChange={e=>setPlans(v=>v.map((x,j)=>j===i?{...x,is_active:e.target.checked}:x))}/> Ativo</label></article>)}</div></section>;
};
