import React, { useEffect, useState } from 'react';
import { Eye, History, Save, Settings2 } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../lib/supabase';
import { useAuth } from '../../hooks/useAuth';

type Config={page_mode:'global'|'member'|'vip'|'creator';member_page_title:string;member_page_subtitle:string;vip_page_title:string;vip_page_subtitle:string;creator_page_title:string;creator_page_subtitle:string;brand_name:string;logo_url:string;hero_title:string;hero_subtitle:string;hero_image_url:string;primary_color:string;faq_text:string;help_text:string;terms_url:string;privacy_url:string;short_video_enabled:boolean;long_video_enabled:boolean;lives_enabled:boolean;stories_enabled:boolean;polls_enabled:boolean;badges_enabled:boolean;comments_enabled:boolean;sharing_enabled:boolean;creator_signup_enabled:boolean;ads_enabled:boolean;ppv_enabled:boolean;tips_enabled:boolean;creator_subscriptions_enabled:boolean;maintenance_mode:boolean;require_creator_approval:boolean;require_age_confirmation:boolean;max_upload_mb:number;max_short_seconds:number;max_long_minutes:number;max_highlights_per_creator:number;max_live_minutes:number;max_daily_posts:number;min_withdrawal_amount:number;creator_min_price:number;creator_max_price:number};
const defaults:Config={page_mode:'global',member_page_title:'Membro Velvet VIP',member_page_subtitle:'Descubra conteúdos e criadores.',vip_page_title:'Membro VIP',vip_page_subtitle:'Acesso premium aos seus criadores favoritos.',creator_page_title:'Creator Studio',creator_page_subtitle:'Publique, faça lives e monetize sua comunidade.',brand_name:'Velvet VIP',logo_url:'',hero_title:'Conteúdo exclusivo. Conexões reais.',hero_subtitle:'Descubra criadores e experiências premium.',hero_image_url:'',primary_color:'#e11d48',faq_text:'',help_text:'',terms_url:'',privacy_url:'',short_video_enabled:true,long_video_enabled:true,lives_enabled:true,stories_enabled:true,polls_enabled:true,badges_enabled:true,comments_enabled:true,sharing_enabled:true,creator_signup_enabled:true,ads_enabled:true,ppv_enabled:true,tips_enabled:true,creator_subscriptions_enabled:true,maintenance_mode:false,require_creator_approval:true,require_age_confirmation:true,max_upload_mb:500,max_short_seconds:90,max_long_minutes:120,max_highlights_per_creator:20,max_live_minutes:240,max_daily_posts:20,min_withdrawal_amount:50,creator_min_price:5,creator_max_price:999.90};

export const AdminEditor:React.FC=()=>{
 const {currentUser}=useAuth(); const [form,setForm]=useState<Config>(defaults); const [saved,setSaved]=useState<Config>(defaults); const [history,setHistory]=useState<any[]>([]); const [preview,setPreview]=useState(false); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState('');
 const load=async()=>{if(!supabase||!isSupabaseConfigured)return; const [{data},{data:h}]=await Promise.all([supabase.from('app_content_settings').select('*').eq('id','global').maybeSingle(),supabase.from('admin_change_log').select('*').eq('entity','app_content_settings').order('created_at',{ascending:false}).limit(20)]); if(data){const v={...defaults,...data};setForm(v);setSaved(v)} setHistory(h||[])};
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!supabase||!currentUser)return;setSaving(true);setMsg('');const payload={id:'global',...form,updated_by:currentUser.id,updated_at:new Date().toISOString()};const {error}=await supabase.from('app_content_settings').upsert(payload);if(!error){await supabase.from('admin_change_log').insert({entity:'app_content_settings',entity_id:'global',action:'publish',before_data:saved,after_data:form,changed_by:currentUser.id});setSaved(form);setMsg('Alterações publicadas.');await load()}else setMsg(error.message);setSaving(false)};
 const toggle=(k:keyof Config,label:string)=><label className="flex items-center justify-between rounded-xl border border-zinc-800 p-3 text-sm"><span>{label}</span><input type="checkbox" checked={Boolean(form[k])} onChange={e=>setForm({...form,[k]:e.target.checked})}/></label>;
 if(currentUser?.role!=='admin')return <div className="p-6 text-zinc-400">Acesso restrito.</div>;
 return <section className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Painel de edição</h2><p className="text-sm text-zinc-500">Edite a experiência sem alterar código.</p></div><div className="flex gap-2"><button onClick={()=>setPreview(!preview)} className="rounded-xl border border-zinc-700 px-3 py-2 text-xs font-bold"><Eye className="mr-1 inline h-4 w-4"/>Prévia</button><button onClick={save} disabled={saving} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-bold"><Save className="mr-1 inline h-4 w-4"/>{saving?'Publicando...':'Publicar'}</button></div></div>
  {msg&&<p className="rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-xs">{msg}</p>}
  <div className="rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4">
   <h3 className="font-bold">Página que será editada</h3>
   <p className="mt-1 text-xs text-zinc-500">Agora o administrador pode editar separadamente a experiência do membro, membro VIP e criador.</p>
   <div className="mt-3 grid gap-2 sm:grid-cols-4">
    {([['global','Página inicial'],['member','Página do membro'],['vip','Página do membro VIP'],['creator','Página do criador']] as const).map(([mode,label])=><button key={mode} onClick={()=>setForm({...form,page_mode:mode})} className={`rounded-xl border px-3 py-2 text-xs font-bold ${form.page_mode===mode?'border-rose-500 bg-rose-600 text-white':'border-zinc-700 bg-zinc-950 text-zinc-400 hover:text-white'}`}>{label}</button>)}
   </div>
  </div>
  {form.page_mode!=='global'&&<div className="grid gap-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4 md:grid-cols-2">
   {form.page_mode==='member'&&<><label className="block text-xs text-zinc-400">Título do membro<input value={form.member_page_title} onChange={e=>setForm({...form,member_page_title:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label><label className="block text-xs text-zinc-400">Subtítulo<input value={form.member_page_subtitle} onChange={e=>setForm({...form,member_page_subtitle:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label></>}
   {form.page_mode==='vip'&&<><label className="block text-xs text-zinc-400">Título do membro VIP<input value={form.vip_page_title} onChange={e=>setForm({...form,vip_page_title:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label><label className="block text-xs text-zinc-400">Subtítulo<input value={form.vip_page_subtitle} onChange={e=>setForm({...form,vip_page_subtitle:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label></>}
   {form.page_mode==='creator'&&<><label className="block text-xs text-zinc-400">Título do criador<input value={form.creator_page_title} onChange={e=>setForm({...form,creator_page_title:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label><label className="block text-xs text-zinc-400">Subtítulo<input value={form.creator_page_subtitle} onChange={e=>setForm({...form,creator_page_subtitle:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label></>}
  </div>}
  {preview&&<div className="overflow-hidden rounded-3xl border border-zinc-800 bg-black"><div className="p-6" style={{borderBottom:`3px solid ${form.primary_color}`}}><p className="text-xs text-zinc-500">PRÉVIA MOBILE/DESKTOP</p><h3 className="mt-5 text-3xl font-black">{form.hero_title}</h3><p className="mt-2 text-zinc-400">{form.hero_subtitle}</p><button className="mt-5 rounded-xl px-4 py-2 text-sm font-bold" style={{background:form.primary_color}}>Começar</button></div></div>}
  <div className="grid gap-4 lg:grid-cols-2">
   <div className="space-y-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="font-bold">Aparência e página inicial</h3>{([['brand_name','Nome da plataforma'],['logo_url','URL da logo'],['hero_title','Título principal'],['hero_subtitle','Subtítulo'],['hero_image_url','Imagem/banner'],['primary_color','Cor principal']] as const).map(([k,l])=><label key={k} className="block text-xs text-zinc-400">{l}<input value={String(form[k])} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-white"/></label>)}</div>
   <div className="space-y-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="font-bold"><Settings2 className="mr-2 inline h-4 w-4"/>Recursos</h3>{toggle('short_video_enabled','Vídeos curtos')}{toggle('long_video_enabled','Vídeos longos')}{toggle('lives_enabled','Lives')}{toggle('stories_enabled','Stories')}{toggle('polls_enabled','Enquetes')}{toggle('badges_enabled','Badges')}{toggle('comments_enabled','Comentários')}{toggle('sharing_enabled','Compartilhamento')}{toggle('creator_signup_enabled','Cadastro de criadores')}{toggle('ads_enabled','Anúncios')}{toggle('ppv_enabled','PPV / compra avulsa')}{toggle('tips_enabled','Gorjetas')}{toggle('creator_subscriptions_enabled','Assinaturas de criadores')}</div>
   <div className="space-y-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="font-bold">Limites</h3>{([['max_upload_mb','Upload máximo (MB)'],['max_short_seconds','Vídeo curto máximo (segundos)'],['max_long_minutes','Vídeo longo máximo (minutos)'],['max_highlights_per_creator','Destaques máximos por criador'],['max_live_minutes','Duração máxima de live (minutos)'],['max_daily_posts','Publicações máximas por dia'],['min_withdrawal_amount','Saque mínimo (R$)'],['creator_min_price','Preço mínimo do criador (R$)'],['creator_max_price','Preço máximo do criador (R$)']] as const).map(([k,l])=><label key={k} className="block text-xs text-zinc-400">{l}<input type="number" min="1" value={Number(form[k])} onChange={e=>setForm({...form,[k]:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/></label>)}</div>
   <div className="space-y-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="font-bold">Segurança e operação</h3>{toggle('require_age_confirmation','Confirmação 18+ obrigatória')}{toggle('require_creator_approval','Aprovação manual de criadores')}{toggle('maintenance_mode','Modo manutenção')}<p className="text-[11px] text-zinc-500">Alterações são persistidas no Supabase e registradas no histórico administrativo.</p></div>
   <div className="space-y-3 rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="font-bold">Textos e páginas</h3>{([['faq_text','FAQ'],['help_text','Ajuda'],['terms_url','Termos'],['privacy_url','Privacidade']] as const).map(([k,l])=><label key={k} className="block text-xs text-zinc-400">{l}{k.endsWith('_text')?<textarea value={String(form[k])} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 min-h-20 w-full rounded-xl border border-zinc-700 bg-zinc-950 p-3 text-sm"/>:<input value={String(form[k])} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm"/>}</label>)}</div>
  </div>
  <div className="rounded-3xl border border-zinc-800 bg-zinc-900/60 p-4"><h3 className="mb-3 font-bold"><History className="mr-2 inline h-4 w-4"/>Histórico de publicação</h3>{history.length?history.map(h=><div key={h.id} className="border-t border-zinc-800 py-2 text-xs text-zinc-400">{new Date(h.created_at).toLocaleString('pt-BR')} • {h.action}</div>):<p className="text-xs text-zinc-500">Nenhuma alteração registrada.</p>}</div>
 </section>
}