import { useMemo, useState } from "react";
import { MapPin, Search, ShoppingBag, Plus, Minus, Trash2, X, Heart, Package, User, Store, Bike, ShieldCheck, LayoutDashboard, ChevronRight, Bell, Map, Clock, CreditCard, Truck, CheckCircle2, ArrowLeft, Tag, MessageCircle, Settings, LogOut } from "lucide-react";

type Role = "customer" | "vendor" | "delivery" | "admin";
type Product = { id:number; name:string; vendor:string; fair:string; price:number; category:string; emoji:string; stock:number };
type OrderStatus = "Recebido" | "Preparando" | "Coleta" | "Em rota" | "Entregue" | "Cancelado";

const categories = ["Hortifruti","Carnes","Queijos","Padaria","Doces","Comidas prontas","Moda","Artesanato","Casa","Plantas","Presentes"];
const products:Product[] = [
 {id:1,name:"Cesta de frutas",vendor:"Sítio da Vó",fair:"Feira do Produtor",price:24.9,category:"Hortifruti",emoji:"🍎",stock:30},
 {id:2,name:"Queijo artesanal",vendor:"Queijaria do Cerrado",fair:"Feira do Produtor",price:32,category:"Queijos",emoji:"🧀",stock:18},
 {id:3,name:"Bolo de milho",vendor:"Delícias da Feira",fair:"Feira Central",price:18,category:"Doces",emoji:"🌽",stock:12},
 {id:4,name:"Cesta de pães",vendor:"Forno da Praça",fair:"Feira Central",price:21.5,category:"Padaria",emoji:"🥖",stock:25},
 {id:5,name:"Planta ornamental",vendor:"Verde Cerrado",fair:"Feira de Artesanato",price:28,category:"Plantas",emoji:"🪴",stock:9},
 {id:6,name:"Bolsa artesanal",vendor:"Mãos do DF",fair:"Feira de Artesanato",price:69.9,category:"Artesanato",emoji:"👜",stock:7},
 {id:7,name:"Mel artesanal",vendor:"Apiário Cerrado",fair:"Feira Central",price:28,category:"Doces",emoji:"🍯",stock:15},
 {id:8,name:"Pastel de carne",vendor:"Pastelaria da Feira",fair:"Feira do Produtor",price:9.5,category:"Comidas prontas",emoji:"🥟",stock:40}
];
const fairs = [
 {name:"Feira do Produtor",place:"Planaltina",status:"Aberta agora",vendors:48,distance:"1,8 km",lat:-15.836,lng:-47.934},
 {name:"Feira Central",place:"Brasília",status:"Aberta agora",vendors:31,distance:"28,4 km",lat:-15.80,lng:-47.89},
 {name:"Feira de Artesanato",place:"Brasília",status:"Abre às 18h",vendors:22,distance:"30,1 km",lat:-15.78,lng:-47.91}
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function App(){
 const [role,setRole]=useState<Role>("customer");
 const [availableRoles,setAvailableRoles]=useState<Role[]>(["customer","vendor","delivery"]);
 const [tab,setTab]=useState("home");
 const [screen,setScreen]=useState("main");
 const [query,setQuery]=useState("");
 const [category,setCategory]=useState("Todos");
 const [cart,setCart]=useState<Record<number,number>>({});
 const [cartOpen,setCartOpen]=useState(false);
 const [location,setLocation]=useState("Planaltina, DF");
 const [favorites,setFavorites]=useState<number[]>([2]);
 const [notifications,setNotifications]=useState(2);
 const [delivery,setDelivery]=useState<"delivery"|"pickup">("delivery");
 const [payment,setPayment]=useState("Pix");
 const [orderPlaced,setOrderPlaced]=useState(false);

 const filtered=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&(!query||[p.name,p.vendor,p.fair,p.category].join(" ").toLowerCase().includes(query.toLowerCase()))),[query,category]);
 const items=products.filter(p=>cart[p.id]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 const subtotal=items.reduce((s,p)=>s+p.price*cart[p.id],0);
 const deliveryFee=delivery==="delivery"?(subtotal>=80?0:8.9):0;
 const total=subtotal+deliveryFee;

 const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
 const remove=(id:number)=>setCart(c=>{const n={...c};if(!n[id])return n;if(n[id]===1)delete n[id];else n[id]--;return n});
 const gps=()=>{if(!navigator.geolocation){setLocation("Informe sua localização");return}navigator.geolocation.getCurrentPosition(()=>setLocation("Minha localização"),()=>setLocation("Localização manual"))};
 const map=(lat:number,lng:number)=>window.open("https://www.google.com/maps/dir/?api=1&destination="+lat+","+lng,"_blank");
 const go=(s:string)=>{setScreen(s);setTab("home")};
 const toggleFavorite=(id:number)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const switchRole=(next:Role)=>{if(next==="admin"||availableRoles.includes(next)){setRole(next);setScreen("main");setTab("home");setCartOpen(false)}};

 return <div className="min-h-screen bg-[#f7f8f3] text-slate-900 pb-20">
  <header className="sticky top-0 z-40 border-b border-black/5 bg-white/95 backdrop-blur">
   <div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-4 py-3">
    <button onClick={()=>{switchRole("customer");go("main");setTab("home")}} className="mr-1 text-left"><b className="text-2xl font-black text-green-700">Feiraê<span className="text-amber-500">.</span></b><small className="hidden sm:block text-[10px] font-bold uppercase tracking-widest text-slate-400">A feira do seu jeito</small></button>
    <button onClick={gps} className="hidden rounded-xl bg-green-50 px-3 py-2 text-xs font-bold text-green-800 md:flex items-center gap-1"><MapPin size={15}/>{location}</button>
    <div className="relative flex-1 min-w-[180px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value){setTab("products");go("main")}}} placeholder="O que você procura na feira?" className="w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 outline-none focus:border-green-500"/></div>
    <button onClick={()=>go("notifications")} className="relative rounded-2xl border bg-white p-3"><Bell size={20}/>{notifications>0&&<span className="absolute -right-1 -top-1 rounded-full bg-amber-400 px-1.5 text-xs font-black">{notifications}</span>}</button>
    <button onClick={()=>setCartOpen(true)} className="relative rounded-2xl bg-green-700 p-3 text-white"><ShoppingBag size={20}/>{count>0&&<span className="absolute -right-1 -top-1 rounded-full bg-amber-400 px-1.5 text-xs font-black text-slate-900">{count}</span>}</button>
   </div>
  </header>

  {screen==="main"&&role==="customer"&&<main className="mx-auto max-w-7xl px-4 py-6">
   {tab==="home"&&<Home setTab={setTab} setScreen={setScreen} map={map} category={category} setCategory={setCategory} />}
   {tab==="fairs"&&<Fairs setScreen={setScreen} map={map}/>}
   {tab==="products"&&<Catalog products={filtered} category={category} setCategory={setCategory} add={add} favorites={favorites} toggleFavorite={toggleFavorite}/>}
   {tab==="orders"&&<Orders go={go}/>}
   {tab==="profile"&&<Profile go={go} setRole={setRole}/>}
  </main>}

  {screen==="fair"&&<FairDetail onBack={()=>go("main")} map={map} add={add}/>}
  {screen==="vendor"&&<VendorStore onBack={()=>go("main")} add={add} favorites={favorites} toggleFavorite={toggleFavorite}/>}
  {screen==="tracking"&&<DeliveryTracking/>}
  {screen==="checkout"&&<Checkout items={items} cart={cart} subtotal={subtotal} delivery={delivery} setDelivery={setDelivery} deliveryFee={deliveryFee} total={total} payment={payment} setPayment={setPayment} onBack={()=>setScreen("main")} onPlace={()=>{setOrderPlaced(true);setCart({});setCartOpen(false);setScreen("orders");setTab("orders")}}/>}
  {screen==="favorites"&&<Favorites ids={favorites} add={add} toggleFavorite={toggleFavorite}/>}
  {screen==="notifications"&&<Notifications clear={()=>{setNotifications(0);setScreen("main")}}/>}
  {screen==="addresses"&&<Addresses/>}
  {screen==="chat"&&<Chat/>}
  {screen==="vendorOps"&&<VendorOperations/>}
  {screen==="deliveryOps"&&<DeliveryOperations/>}
  {screen==="adminOps"&&<AdminOperations/>}

  {role!=="customer"&&screen==="main"&&<Dashboard role={role} setScreen={setScreen}/>}
  {role==="customer"&&<nav className="fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 p-2 md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1">
   <button onClick={()=>{setTab("home");go("main")}} className="rounded-xl p-2 text-xs font-bold">⌂<br/>Início</button>
   <button onClick={()=>{setTab("fairs");go("main")}} className="rounded-xl p-2 text-xs font-bold">🧺<br/>Feiras</button>
   <button onClick={()=>{setTab("orders");go("main")}} className="rounded-xl p-2 text-xs font-bold">📦<br/>Pedidos</button>
   <button onClick={()=>{setTab("profile");go("main")}} className="rounded-xl p-2 text-xs font-bold">👤<br/>Perfil</button>
  </div></nav>}
  {role!=="admin"&&<div className="fixed bottom-20 right-3 z-30 hidden rounded-2xl border bg-white p-2 shadow-lg md:flex items-center gap-1"><span className="px-2 text-[10px] font-black uppercase text-slate-400">Modo</span>{availableRoles.map(r=><button key={r} onClick={()=>switchRole(r)} className={`rounded-xl px-3 py-2 text-xs font-bold ${role===r?"bg-green-700 text-white":"hover:bg-slate-100"}`}>{r==="customer"?"Cliente":r==="vendor"?"Feirante":"Entregador"}</button>)}</div>\n  {role==="customer"&&<nav className="fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 p-2 md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1"><button onClick={()=>{setTab("home");go("main")}} className="rounded-xl p-2 text-xs font-bold">⌂<br/>Início</button><button onClick={()=>{setTab("fairs");go("main")}} className="rounded-xl p-2 text-xs font-bold">🧺<br/>Feiras</button><button onClick={()=>{setTab("orders");go("main")}} className="rounded-xl p-2 text-xs font-bold">📦<br/>Pedidos</button><button onClick={()=>{setTab("profile");go("main")}} className="rounded-xl p-2 text-xs font-bold">👤<br/>Perfil</button></div></nav>}\n  {role==="vendor"&&<nav className="fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 p-2 md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1"><button onClick={()=>setScreen("main")} className="rounded-xl p-2 text-xs font-bold">▦<br/>Painel</button><button onClick={()=>setScreen("vendorOps")} className="rounded-xl p-2 text-xs font-bold">📦<br/>Pedidos</button><button onClick={()=>setScreen("vendorOps")} className="rounded-xl p-2 text-xs font-bold">🏪<br/>Loja</button><button onClick={()=>switchRole("customer")} className="rounded-xl p-2 text-xs font-bold">👤<br/>Cliente</button></div></nav>}\n  {role==="delivery"&&<nav className="fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 p-2 md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1"><button onClick={()=>setScreen("main")} className="rounded-xl p-2 text-xs font-bold">▦<br/>Central</button><button onClick={()=>setScreen("deliveryOps")} className="rounded-xl p-2 text-xs font-bold">🛵<br/>Entregas</button><button onClick={()=>setScreen("deliveryOps")} className="rounded-xl p-2 text-xs font-bold">💰<br/>Ganhos</button><button onClick={()=>switchRole("customer")} className="rounded-xl p-2 text-xs font-bold">👤<br/>Cliente</button></div></nav>}

  {cartOpen&&<Cart items={items} cart={cart} add={add} remove={remove} total={subtotal} onClose={()=>setCartOpen(false)} onCheckout={()=>setScreen("checkout")}/>}
  {orderPlaced&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-2xl bg-green-800 px-5 py-3 text-sm font-bold text-white shadow-xl">Pedido FE-1027 criado no modo demonstração.</div>}
 </div>
}

function Home({setTab,setScreen,map,category,setCategory}:{setTab:(x:string)=>void;setScreen:(x:string)=>void;map:(a:number,b:number)=>void;category:string;setCategory:(x:string)=>void}){
 return <><section className="relative overflow-hidden rounded-[2rem] bg-green-800 p-8 text-white sm:p-12"><div className="max-w-2xl"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">MARKETPLACE DAS FEIRAS DO DF</span><h1 className="mt-4 text-4xl font-black sm:text-5xl">Tudo que você encontra na feira, no seu celular.</h1><p className="mt-4 text-green-50">Descubra feirantes, produtos e feiras perto de você. Compre para receber em casa ou retirar.</p><button onClick={()=>setTab("products")} className="mt-6 rounded-xl bg-amber-400 px-5 py-3 font-black text-slate-950">Explorar produtos →</button></div><div className="absolute -right-5 -top-10 text-[10rem] opacity-20">🧺</div></section>
 <section className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4"><Action title="Minha feira" sub="Entrar em uma feira" icon="🧺" onClick={()=>setScreen("fair")}/><Action title="Loja" sub="Conhecer um feirante" icon="🏪" onClick={()=>setScreen("vendor")}/><Action title="Entrega" sub="Acompanhar pedido" icon="🛵" onClick={()=>setScreen("tracking")}/><Action title="Vender" sub="Área do feirante" icon="🧑‍🌾" onClick={()=>setScreen("vendorOps")}/></section>
 <section className="mt-10"><div className="mb-4 flex justify-between"><div><h2 className="text-xl font-black">Categorias</h2><p className="text-sm text-slate-500">Comida, artesanato, moda e muito mais.</p></div><button onClick={()=>setCategory("Todos")} className="text-sm font-bold text-green-700">Todas</button></div><div className="flex gap-2 overflow-auto pb-2">{["Todos",...categories].map(c=><button key={c} onClick={()=>{setCategory(c);setTab("products")}} className={`whitespace-nowrap rounded-2xl border px-4 py-3 text-xs font-bold ${category===c?"border-green-600 bg-green-50":"border-slate-200 bg-white"}`}>{c}</button>)}</div></section>
 <section className="mt-10"><h2 className="text-xl font-black">Feiras em destaque</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{fairs.map(f=><article key={f.name} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex h-28 items-end bg-gradient-to-br from-green-100 to-amber-50 p-4 text-4xl">🧺</div><div className="p-4"><div className="flex justify-between gap-2"><h3 className="font-black">{f.name}</h3><span className="text-[10px] font-black text-green-700">{f.status}</span></div><p className="mt-2 text-xs text-slate-500"><MapPin size={12} className="inline"/> {f.place} · {f.distance} · {f.vendors} feirantes</p><div className="mt-4 flex gap-2"><button onClick={()=>setScreen("fair")} className="rounded-xl bg-green-700 px-3 py-2 text-xs font-bold text-white">Ver feira</button><button onClick={()=>map(f.lat,f.lng)} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">Como chegar</button></div></div></article>)}</div></section></>
}
function Action({title,sub,icon,onClick}:{title:string;sub:string;icon:string;onClick:()=>void}){return <button onClick={onClick} className="rounded-2xl border bg-white p-4 text-left hover:border-green-400"><b>{icon} {title}</b><small className="block text-slate-500">{sub}</small></button>}

function Fairs({setScreen,map}:{setScreen:(x:string)=>void;map:(a:number,b:number)=>void}){return <section><h1 className="text-3xl font-black">Feiras</h1><p className="text-slate-500">Escolha onde quer comprar.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{fairs.map(f=><article key={f.name} className="rounded-3xl border bg-white p-5"><div className="text-5xl">🧺</div><h2 className="mt-4 font-black">{f.name}</h2><p className="text-sm text-slate-500">{f.place} · {f.distance}</p><button onClick={()=>setScreen("fair")} className="mt-5 w-full rounded-xl bg-green-700 py-3 font-bold text-white">Entrar na feira</button><button onClick={()=>map(f.lat,f.lng)} className="mt-2 w-full rounded-xl bg-slate-100 py-3 font-bold">Como chegar</button></article>)}</div></section>}

function Catalog({products,category,setCategory,add,favorites,toggleFavorite}:{products:Product[];category:string;setCategory:(x:string)=>void;add:(id:number)=>void;favorites:number[];toggleFavorite:(id:number)=>void}){return <section><div className="flex items-end justify-between"><div><h1 className="text-3xl font-black">Catálogo</h1><p className="text-slate-500">{products.length} produtos encontrados.</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-800">Marketplace</span></div><div className="mt-4 flex gap-2 overflow-auto pb-2">{["Todos",...categories].map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-bold ${category===c?"bg-green-700 text-white":"bg-white border"}`}>{c}</button>)}</div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} p={p} add={add} favorite={favorites.includes(p.id)} toggleFavorite={toggleFavorite}/>)}</div></section>}
function ProductCard({p,add,favorite,toggleFavorite}:{p:Product;add:(id:number)=>void;favorite?:boolean;toggleFavorite?:(id:number)=>void}){return <article className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><button onClick={()=>toggleFavorite?.(p.id)} className="absolute right-2 top-2 z-10 rounded-full bg-white/90 p-2 shadow"><Heart size={16} className={favorite?"fill-red-500 text-red-500":""}/></button><div className="flex aspect-square items-center justify-center bg-gradient-to-br from-lime-50 to-amber-50 text-6xl">{p.emoji}</div><div className="p-3"><small className="font-bold text-green-700">{p.vendor}</small><h3 className="mt-1 font-black">{p.name}</h3><p className="text-[11px] text-slate-400">{p.fair} · {p.stock} disponíveis</p><div className="mt-3 flex items-center justify-between"><b>{money(p.price)}</b><button onClick={()=>add(p.id)} className="rounded-xl bg-green-700 p-2 text-white"><Plus size={17}/></button></div></div></article>}

function Cart({items,cart,add,remove,total,onClose,onCheckout}:{items:Product[];cart:Record<number,number>;add:(id:number)=>void;remove:(id:number)=>void;total:number;onClose:()=>void;onCheckout:()=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40"><aside className="flex h-full w-full max-w-md flex-col bg-white"><div className="flex justify-between border-b p-5"><div><h2 className="text-xl font-black">Minha Feira</h2><small>{Object.values(cart).reduce((a,b)=>a+b,0)} item(ns)</small></div><button onClick={onClose}><X/></button></div><div className="flex-1 overflow-auto p-5">{items.length?items.map(p=><div key={p.id} className="mb-3 rounded-2xl border p-3"><div className="flex gap-3"><span className="text-3xl">{p.emoji}</span><div className="flex-1"><b>{p.name}</b><small className="block text-slate-500">{p.vendor}</small><div className="mt-2 flex justify-between"><strong>{money(p.price*cart[p.id])}</strong><span><button onClick={()=>remove(p.id)}><Minus size={15}/></button> {cart[p.id]} <button onClick={()=>add(p.id)}><Plus size={15}/></button></span></div></div><button onClick={()=>{for(let i=0;i<cart[p.id];i++)remove(p.id)}}><Trash2 size={15}/></button></div></div>):<div className="py-20 text-center"><ShoppingBag className="mx-auto text-slate-300" size={45}/><p className="font-bold">Sua sacola está vazia.</p></div>}</div>{items.length>0&&<div className="border-t p-5"><div className="flex justify-between"><span>Subtotal</span><b>{money(total)}</b></div><button className="mt-4 w-full rounded-2xl bg-green-700 py-4 font-black text-white" onClick={onCheckout}>Continuar para checkout</button></div>}</aside></div>}

function Checkout({items,cart,subtotal,delivery,setDelivery,deliveryFee,total,payment,setPayment,onBack,onPlace}:{items:Product[];cart:Record<number,number>;subtotal:number;delivery:"delivery"|"pickup";setDelivery:(x:"delivery"|"pickup")=>void;deliveryFee:number;total:number;payment:string;setPayment:(x:string)=>void;onBack:()=>void;onPlace:()=>void}){return <FeaturePanel title="Finalizar pedido" subtitle="Confira a compra antes de confirmar"><button onClick={onBack} className="mb-5 flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2 font-bold"><ArrowLeft size={16}/> Voltar</button><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Box title="1. Como receber"><div className="grid grid-cols-2 gap-3"><Choice active={delivery==="delivery"} onClick={()=>setDelivery("delivery")} icon={<Truck/>} title="Entrega" text="Receba em casa"/><Choice active={delivery==="pickup"} onClick={()=>setDelivery("pickup")} icon={<Store/>} title="Retirada" text="Na feira"/></div></Box>{delivery==="delivery"&&<Box title="2. Endereço"><div className="rounded-2xl bg-slate-50 p-4"><b>Casa</b><p className="text-sm text-slate-500">Planaltina, DF · endereço de demonstração</p><button className="mt-2 text-xs font-bold text-green-700">Alterar endereço</button></div></Box>}<Box title={delivery==="delivery"?"3. Pagamento":"2. Pagamento"}><div className="grid gap-2 sm:grid-cols-3">{["Pix","Cartão","Dinheiro"].map(x=><Choice key={x} active={payment===x} onClick={()=>setPayment(x)} icon={<CreditCard/>} title={x} text={x==="Pix"?"Aprovação rápida":"No modo demonstração"}/>)}</div></Box><Box title="Itens"><div className="space-y-3">{items.map(p=><div key={p.id} className="flex justify-between border-b pb-3"><span>{cart[p.id]}× {p.name}</span><b>{money(p.price*cart[p.id])}</b></div>)}</div></Box></div><aside className="h-fit rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Resumo</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="flex justify-between"><span>{delivery==="delivery"?"Entrega":"Retirada"}</span><b>{deliveryFee?money(deliveryFee):"Grátis"}</b></div><div className="border-t pt-3 flex justify-between text-lg"><b>Total</b><b className="text-green-700">{money(total)}</b></div></div><button onClick={onPlace} className="mt-6 w-full rounded-2xl bg-green-700 py-4 font-black text-white">Confirmar pedido</button><p className="mt-3 text-center text-[11px] text-slate-400">Pagamento real será conectado na última fase.</p></aside></div></FeaturePanel>}
function Box({title,children}:{title:string;children:any}){return <div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-black">{title}</h2>{children}</div>}
function Choice({active,onClick,icon,title,text}:{active:boolean;onClick:()=>void;icon:any;title:string;text:string}){return <button onClick={onClick} className={`rounded-2xl border p-4 text-left ${active?"border-green-600 bg-green-50":"bg-white"}`}><div className="flex items-center gap-2 text-green-700">{icon}<b>{title}</b></div><small className="text-slate-500">{text}</small></button>}

function Orders({go}:{go:(s:string)=>void}){return <section className="mx-auto max-w-3xl"><h1 className="text-3xl font-black">Meus pedidos</h1><p className="text-slate-500">Acompanhe compras, retirada e entrega.</p><div className="mt-5 space-y-3"><Order id="FE-1027" date="20/09/2026" status="Recebido" value={86.8} go={go}/><Order id="FE-1024" date="20/09/2026" status="Em rota" value={58.7} go={go}/><Order id="FE-1019" date="19/09/2026" status="Entregue" value={42.9} go={go}/></div></section>}
function Order({id,date,status,value,go}:{id:string;date:string;status:OrderStatus;value:number;go:(s:string)=>void}){return <article className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><b>{id}</b><p className="text-xs text-slate-500">{date} · Feiraê</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-800">{status}</span></div><div className="mt-4 flex justify-between"><b>{money(value)}</b><button onClick={()=>go("tracking")} className="rounded-xl bg-green-700 px-4 py-2 text-xs font-bold text-white">Acompanhar</button></div></article>}

function Profile({go,setRole}:{go:(s:string)=>void;setRole:(r:Role)=>void}){return <section className="mx-auto max-w-2xl py-4"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-green-100 text-2xl">👤</div><div><h1 className="text-2xl font-black">Meu perfil</h1><p className="text-sm text-slate-500">Cliente Feiraê</p></div></div><div className="mt-6 rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><b>Modo atual</b><p className="text-xs text-slate-500">Uma conta, experiências diferentes.</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-black text-green-700">Cliente</span></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setRole("vendor")} className="rounded-xl border p-3 text-left text-xs font-bold">🧑‍🌾 Feirante<small className="mt-1 block font-normal text-slate-500">Gerenciar minha loja</small></button><button onClick={()=>setRole("delivery")} className="rounded-xl border p-3 text-left text-xs font-bold">🛵 Entregador<small className="mt-1 block font-normal text-slate-500">Aceitar entregas</small></button></div></div><div className="mt-6 grid gap-2">{[["Meus endereços","addresses",<MapPin/>],["Favoritos","favorites",<Heart/>],["Notificações","notifications",<Bell/>],["Conversar com suporte","chat",<MessageCircle/>]].map(([x,s,i])=><button key={String(s)} onClick={()=>go(String(s))} className="flex items-center justify-between rounded-2xl border bg-white p-4 text-left font-bold"><span className="flex items-center gap-3 text-green-700">{i}<span className="text-slate-900">{String(x)}</span></span><ChevronRight/></button>)}<button onClick={()=>setRole("vendor");setScreen("main")} className="flex justify-between rounded-2xl border bg-white p-4 font-bold">Quero vender no Feiraê<ChevronRight/></button><button className="mt-4 flex items-center gap-2 rounded-2xl border bg-white p-4 font-bold text-slate-500"><Settings/> Configurações</button></div></section>}

function FairDetail({onBack,map,add}:{onBack:()=>void;map:(a:number,b:number)=>void;add:(id:number)=>void}){const fair=fairs[0];const ps=products.filter(p=>p.fair===fair.name);return <FeaturePanel title={fair.name} subtitle={fair.place+" · "+fair.status}><Back onBack={onBack}/><div className="grid gap-4 md:grid-cols-3"><Box title="Localização"><p className="text-sm text-slate-500">{fair.place}</p><button onClick={()=>map(fair.lat,fair.lng)} className="mt-3 text-xs font-bold text-green-700">Abrir rota</button></Box><Box title="Horários"><p className="text-sm text-slate-500">Consulte a programação da feira.</p></Box><Box title="Feirantes"><p className="text-2xl font-black">{fair.vendors}</p><p className="text-xs text-slate-500">participantes cadastrados</p></Box></div><h2 className="mt-8 text-xl font-black">Produtos desta feira</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{ps.map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></FeaturePanel>}
function VendorStore({onBack,add,favorites,toggleFavorite}:{onBack:()=>void;add:(id:number)=>void;favorites:number[];toggleFavorite:(id:number)=>void}){const ps=products.filter(p=>p.vendor==="Sítio da Vó");return <FeaturePanel title="Sítio da Vó" subtitle="Loja do feirante"><Back onBack={onBack}/><div className="rounded-3xl bg-green-800 p-7 text-white"><Store/><h2 className="mt-3 text-2xl font-black">Sítio da Vó</h2><p className="text-green-100">Hortifruti selecionado direto da feira.</p><div className="mt-4 flex gap-2 text-xs"><span className="rounded-full bg-white/15 px-3 py-1">⭐ 4,9</span><span className="rounded-full bg-white/15 px-3 py-1">Planaltina</span></div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{ps.map(p=><ProductCard key={p.id} p={p} add={add} favorite={favorites.includes(p.id)} toggleFavorite={toggleFavorite}/>)}</div></FeaturePanel>}
function Back({onBack}:{onBack:()=>void}){return <button onClick={onBack} className="mb-5 flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2 font-bold"><ArrowLeft size={16}/> Voltar</button>}
function DeliveryTracking(){return <FeaturePanel title="Acompanhar entrega" subtitle="Pedido FE-1024"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-green-800 p-8 text-white"><div className="text-6xl">🛵</div><h2 className="mt-4 text-2xl font-black">Seu pedido está a caminho</h2><p className="mt-2 text-green-100">Previsão: 20–35 min.</p><div className="mt-7 h-3 rounded-full bg-white/20"><div className="h-3 w-3/4 rounded-full bg-amber-400"/></div><div className="mt-4 flex justify-between text-xs"><span>Preparando</span><span>Coletado</span><b>Em rota</b><span>Entregue</span></div></div><div className="rounded-3xl border bg-white p-6"><h3 className="font-black">Linha do pedido</h3><div className="mt-5 space-y-4">{["Pedido confirmado","Produtos separados pelos feirantes","Coleta concluída","Entregador em rota"].map((x,i)=><div key={x} className="flex gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-green-100 text-green-700">{i<3?"✓":"•"}</span><span className="font-semibold">{x}</span></div>)}</div></div></div></FeaturePanel>}
function Favorites({ids,add,toggleFavorite}:{ids:number[];add:(id:number)=>void;toggleFavorite:(id:number)=>void}){const ps=products.filter(p=>ids.includes(p.id));return <FeaturePanel title="Favoritos" subtitle="Produtos que você quer encontrar de novo."><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{ps.length?ps.map(p=><ProductCard key={p.id} p={p} add={add} favorite toggleFavorite={toggleFavorite}/>):<Empty text="Você ainda não favoritou produtos."/>}</div></FeaturePanel>}
function Notifications({clear}:{clear:()=>void}){return <FeaturePanel title="Notificações" subtitle="Atualizações dos seus pedidos e ofertas."><div className="mb-4 flex justify-end"><button onClick={clear} className="text-xs font-bold text-green-700">Marcar como lidas</button></div>{["Seu pedido FE-1024 saiu para entrega.","Novo desconto na Feira do Produtor.","Sítio da Vó adicionou produtos ao catálogo.","Seu pedido FE-1019 foi entregue."].map((x,i)=><div key={x} className={`mb-2 rounded-2xl border p-4 ${i<2?"bg-green-50":"bg-white"}`}><div className="flex gap-3"><Bell className="text-green-700"/><div><b>{x}</b><p className="text-xs text-slate-500">{i+1} h atrás</p></div></div></div>)}</FeaturePanel>}
function Addresses(){return <FeaturePanel title="Meus endereços" subtitle="Onde você quer receber suas compras?"><div className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><div><b>Casa</b><p className="text-sm text-slate-500">Planaltina, DF · endereço de demonstração</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">Principal</span></div></div><button className="mt-4 w-full rounded-2xl border-2 border-dashed p-5 font-bold text-green-700">+ Adicionar endereço</button></FeaturePanel>}
function Chat(){return <FeaturePanel title="Suporte Feiraê" subtitle="Atendimento demonstrativo"><div className="rounded-3xl border bg-white p-5"><div className="rounded-2xl bg-slate-100 p-4 text-sm">Olá! Como podemos ajudar com seu pedido?</div><div className="mt-4 flex gap-2"><input placeholder="Digite sua mensagem..." className="flex-1 rounded-xl border p-3"/><button className="rounded-xl bg-green-700 px-4 text-white"><MessageCircle/></button></div></div></FeaturePanel>}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-3xl border bg-white p-10 text-center text-slate-500">{text}</div>}

function VendorOperations(){const [status,setStatus]=useState("Recebido");return <FeaturePanel title="Operação do feirante" subtitle="Gerencie sua loja no protótipo"><Stats values={[["Pedidos hoje","24"],["Vendas","R$ 1.842"],["Estoque baixo","3"]]}/><div className="mt-6 grid gap-4 lg:grid-cols-2"><Box title="Pedido FE-1027"><p className="text-sm text-slate-500">3 itens · R$ 86,80 · Cliente de Planaltina</p><div className="mt-4 flex flex-wrap gap-2">{["Recebido","Preparando","Coleta"].map(x=><button key={x} onClick={()=>setStatus(x)} className={`rounded-xl px-3 py-2 text-xs font-bold ${status===x?"bg-green-700 text-white":"bg-slate-100"}`}>{x}</button>)}</div><p className="mt-3 text-sm font-bold">Status atual: {status}</p></Box><Box title="Atalhos"><div className="grid grid-cols-2 gap-2">{["Novo produto","Estoque","Promoções","Financeiro","Avaliações","Horários"].map(x=><button key={x} className="rounded-xl border p-4 text-left text-sm font-bold">{x}</button>)}</div></Box></div></FeaturePanel>}
function DeliveryOperations(){const [available,setAvailable]=useState(true);return <FeaturePanel title="Central do entregador" subtitle="Aceite, colete e finalize entregas"><Stats values={[["Disponíveis","8"],["Em rota","2"],["Ganhos hoje","R$ 186,40"]]}/><div className="mt-6 rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-black">Disponibilidade</h2><button onClick={()=>setAvailable(!available)} className={`rounded-full px-4 py-2 text-xs font-bold ${available?"bg-green-100 text-green-800":"bg-slate-100"}`}>{available?"Online":"Offline"}</button></div>{["FE-1024 · Feira do Produtor → Planaltina","FE-1025 · Feira Central → Asa Norte","FE-1026 · Feira de Artesanato → Sudoeste"].map(x=><div key={x} className="mt-3 flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><span className="font-bold">{x}</span><button className="rounded-xl bg-green-700 px-4 py-2 text-sm font-bold text-white">Aceitar</button></div>)}</div></FeaturePanel>}
function AdminOperations(){return <FeaturePanel title="Administração" subtitle="Controle da operação Feiraê"><Stats values={[["126","feirantes"],["12","feiras"],["348","pedidos"],["R$ 28.430","vendas"]]}/><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Aprovar feirantes","Cadastrar feira","Gerenciar categorias","Acompanhar pedidos","Gerenciar entregadores","Financeiro","Relatórios","Denúncias","Configurações"].map(x=><button key={x} className="rounded-2xl border bg-white p-5 text-left"><b>{x}</b><small className="mt-1 block text-slate-500">Abrir módulo</small></button>)}</div></FeaturePanel>}
function Stats({values}:{values:string[][]}){return <div className="grid gap-4 md:grid-cols-4">{values.map(x=><div key={x.join()} className="rounded-3xl border bg-white p-6"><small className="text-slate-500">{x[1]}</small><b className="mt-2 block text-3xl">{x[0]}</b></div>)}</div>}
function Dashboard({role,setScreen}:{role:Role;setScreen:(x:string)=>void}){const vendor=role==="vendor",deliveryRole=role==="delivery";const data=vendor?{icon:<Store/>,title:"Painel do feirante",items:["Dashboard","Pedidos","Produtos","Estoque","Minha loja","Vendas","Financeiro","Avaliações"]}:deliveryRole?{icon:<Bike/>,title:"Central de entregas",items:["Dashboard","Entregas disponíveis","Minhas entregas","Mapa e rotas","Ganhos","Histórico"]}:{icon:<ShieldCheck/>,title:"Painel administrativo",items:["Dashboard","Usuários","Feiras","Feirantes","Entregadores","Pedidos","Categorias","Financeiro","Relatórios"]};return <main className="mx-auto max-w-7xl px-4 py-8"><div className="flex items-center gap-3">{data.icon}<div><small className="font-bold text-green-700">FEIRAÊ</small><h1 className="text-3xl font-black">{data.title}</h1></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><b className="text-xl">24</b><small className="block text-slate-500">pedidos</small></div><div className="rounded-2xl border bg-white p-5"><b className="text-xl">R$ 1.842</b><small className="block text-slate-500">vendas</small></div><div className="rounded-2xl border bg-white p-5"><b className="text-xl">8</b><small className="block text-slate-500">pendentes</small></div><div className="rounded-2xl border bg-white p-5"><b className="text-xl">4,9 ★</b><small className="block text-slate-500">avaliação</small></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.items.map(x=><button key={x} onClick={()=>{if(vendor)setScreen("vendorOps");else if(deliveryRole)setScreen("deliveryOps");else setScreen("adminOps")}} className="rounded-2xl border bg-white p-5 text-left shadow-sm"><LayoutDashboard className="text-green-700"/><b className="mt-3 block">{x}</b><small className="text-slate-500">Gerenciar {x.toLowerCase()}</small></button>)}</div></main>}
function FeaturePanel({title,subtitle,children}:{title:string;subtitle:string;children:any}){return <section className="mx-auto max-w-7xl px-4 py-8"><p className="text-xs font-black uppercase tracking-widest text-green-700">FEIRAÊ</p><h1 className="mt-1 text-3xl font-black">{title}</h1><p className="text-sm text-slate-500">{subtitle}</p><div className="mt-6">{children}</div></section>}
