import { useMemo, useState } from "react";
import { MapPin, Search, ShoppingBag, Plus, Minus, Trash2, X, Heart, Package, User, Store, Bike, ShieldCheck, LayoutDashboard, ChevronRight } from "lucide-react";

type Role="customer"|"vendor"|"delivery"|"admin";
type Product={id:number;name:string;vendor:string;fair:string;price:number;category:string;emoji:string;stock:number};
const categories=["Hortifruti","Carnes","Queijos","Padaria","Doces","Comidas prontas","Moda","Artesanato","Casa","Plantas","Presentes"];
const products:Product[]=[
{id:1,name:"Cesta de frutas",vendor:"Sítio da Vó",fair:"Feira do Produtor",price:24.9,category:"Hortifruti",emoji:"🍎",stock:30},
{id:2,name:"Queijo artesanal",vendor:"Queijaria do Cerrado",fair:"Feira do Produtor",price:32,category:"Queijos",emoji:"🧀",stock:18},
{id:3,name:"Bolo de milho",vendor:"Delícias da Feira",fair:"Feira Central",price:18,category:"Doces",emoji:"🌽",stock:12},
{id:4,name:"Cesta de pães",vendor:"Forno da Praça",fair:"Feira Central",price:21.5,category:"Padaria",emoji:"🥖",stock:25},
{id:5,name:"Planta ornamental",vendor:"Verde Cerrado",fair:"Feira de Artesanato",price:28,category:"Plantas",emoji:"🪴",stock:9},
{id:6,name:"Bolsa artesanal",vendor:"Mãos do DF",fair:"Feira de Artesanato",price:69.9,category:"Artesanato",emoji:"👜",stock:7},
{id:7,name:"Mel artesanal",vendor:"Apiário Cerrado",fair:"Feira Central",price:28,category:"Doces",emoji:"🍯",stock:15},
{id:8,name:"Pastel de carne",vendor:"Pastelaria da Feira",fair:"Feira do Produtor",price:9.5,category:"Comidas prontas",emoji:"🥟",stock:40}
];
const fairs=[
{name:"Feira do Produtor",place:"Planaltina",status:"Aberta agora",vendors:48,distance:"1,8 km",lat:-15.836,lng:-47.934},
{name:"Feira Central",place:"Brasília",status:"Aberta agora",vendors:31,distance:"28,4 km",lat:-15.80,lng:-47.89},
{name:"Feira de Artesanato",place:"Brasília",status:"Abre às 18h",vendors:22,distance:"30,1 km",lat:-15.78,lng:-47.91}
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function App(){
 const [role,setRole]=useState<Role>("customer"),[tab,setTab]=useState("home"),[query,setQuery]=useState(""),[category,setCategory]=useState("Todos"),[cart,setCart]=useState<Record<number,number>>({}),[cartOpen,setCartOpen]=useState(false),[location,setLocation]=useState("Planaltina, DF");
 const filtered=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&(!query||[p.name,p.vendor,p.fair,p.category].join(" ").toLowerCase().includes(query.toLowerCase()))),[query,category]);
 const items=products.filter(p=>cart[p.id]); const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=items.reduce((s,p)=>s+p.price*cart[p.id],0);
 const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1})); const remove=(id:number)=>setCart(c=>{const n={...c};if(!n[id])return n;if(n[id]===1)delete n[id];else n[id]--;return n});
 const gps=()=>{if(!navigator.geolocation){setLocation("Informe sua localização");return} navigator.geolocation.getCurrentPosition(()=>setLocation("Minha localização"),()=>setLocation("Localização manual"))};
 const map=(lat:number,lng:number)=>window.open("https://www.google.com/maps/dir/?api=1&destination="+lat+","+lng,"_blank");
 const customer=role==="customer";
 return <div className="min-h-screen bg-[#f7f8f3] text-slate-900 pb-20">
  <header className="sticky top-0 z-40 border-b border-black/5 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-4 py-3">
   <button onClick={()=>{setRole("customer");setTab("home")}} className="mr-1 text-left"><b className="text-2xl font-black text-green-700">Feiraê<span className="text-amber-500">.</span></b><small className="hidden sm:block text-[10px] font-bold uppercase tracking-widest text-slate-400">A feira do seu jeito</small></button>
   <button onClick={gps} className="hidden rounded-xl bg-green-50 px-3 py-2 text-xs font-bold text-green-800 md:flex items-center gap-1"><MapPin size={15}/>{location}</button>
   <div className="relative flex-1 min-w-[180px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="O que você procura na feira?" className="w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 outline-none focus:border-green-500"/></div>
   <button onClick={()=>setCartOpen(true)} className="relative rounded-2xl bg-green-700 p-3 text-white"><ShoppingBag size={20}/>{count>0&&<span className="absolute -right-1 -top-1 rounded-full bg-amber-400 px-1.5 text-xs font-black text-slate-900">{count}</span>}</button>
  </div></header>
  {customer?<main className="mx-auto max-w-7xl px-4 py-6">
   {tab==="home"&&<><section className="relative overflow-hidden rounded-[2rem] bg-green-800 p-8 text-white sm:p-12"><div className="max-w-2xl"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">MARKETPLACE DAS FEIRAS DO DF</span><h1 className="mt-4 text-4xl font-black sm:text-5xl">Tudo que você encontra na feira, no seu celular.</h1><p className="mt-4 text-green-50">Descubra feirantes, produtos e feiras perto de você. Compre para receber em casa ou retirar.</p><button onClick={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})} className="mt-6 rounded-xl bg-amber-400 px-5 py-3 font-black text-slate-950">Explorar produtos →</button></div><div className="absolute -right-5 -top-10 text-[10rem] opacity-20">🧺</div></section>
   <section className="mt-8"><div className="mb-4 flex justify-between"><h2 className="text-xl font-black">Categorias</h2><button onClick={()=>setCategory("Todos")} className="text-sm font-bold text-green-700">Todas</button></div><div className="flex gap-2 overflow-auto pb-2">{categories.map(c=><button onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-2xl border px-4 py-3 text-xs font-bold ${category===c?"border-green-600 bg-green-50":"border-slate-200 bg-white"}`}>{c}</button>)}</div></section>
   <section className="mt-10"><div className="mb-4"><h2 className="text-xl font-black">Feiras em destaque</h2><p className="text-sm text-slate-500">Encontre uma feira perto de você</p></div><div className="grid gap-4 md:grid-cols-3">{fairs.map(f=><article className="rounded-3xl border border-slate-200 bg-white overflow-hidden shadow-sm"><div className="flex h-28 items-end bg-gradient-to-br from-green-100 to-amber-50 p-4 text-4xl">🧺</div><div className="p-4"><div className="flex justify-between gap-2"><h3 className="font-black">{f.name}</h3><span className="text-[10px] font-black text-green-700">{f.status}</span></div><p className="mt-2 text-xs text-slate-500"><MapPin size={12} className="inline"/> {f.place} · {f.distance} · {f.vendors} feirantes</p><button onClick={()=>map(f.lat,f.lng)} className="mt-4 text-xs font-bold text-green-700">Como chegar →</button></div></article>)}</div></section></>}
   {tab==="fairs"&&<><h1 className="text-3xl font-black">Feiras</h1><p className="text-slate-500">Escolha onde quer comprar.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{fairs.map(f=><article className="rounded-3xl border bg-white p-5"><div className="text-5xl">🧺</div><h2 className="mt-4 font-black">{f.name}</h2><p className="text-sm text-slate-500">{f.place} · {f.distance}</p><button onClick={()=>setTab("products")} className="mt-5 w-full rounded-xl bg-green-700 py-3 font-bold text-white">Entrar na feira</button><button onClick={()=>map(f.lat,f.lng)} className="mt-2 w-full rounded-xl bg-slate-100 py-3 font-bold">Como chegar</button></article>)}</div></>}
   {tab==="products"&&<><h1 className="text-3xl font-black">Catálogo</h1><div className="mt-4 flex gap-2 overflow-auto pb-2">{["Todos",...categories].map(c=><button onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-bold ${category===c?"bg-green-700 text-white":"bg-white border"}`}>{c}</button>)}</div><div id="catalogo" className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{filtered.map(p=><ProductCard p={p} add={add}/>)}</div></>}
   {tab==="orders"&&<section className="mx-auto max-w-2xl py-14"><Package className="text-green-700" size={42}/><h1 className="mt-4 text-3xl font-black">Meus pedidos</h1><div className="mt-5 rounded-3xl border bg-white p-5"><b>FE-1024</b><p className="text-sm text-slate-500">20/09/2026 · 3 itens</p><strong className="text-green-700">Em preparação</strong><p className="mt-3">{money(58.7)}</p><button className="mt-3 rounded-xl bg-green-700 px-4 py-2 text-sm font-bold text-white">Acompanhar pedido</button></div></section>}
   {tab==="profile"&&<section className="mx-auto max-w-2xl py-14"><User className="text-green-700" size={42}/><h1 className="mt-4 text-3xl font-black">Meu perfil</h1><div className="mt-5 grid gap-2">{["Meus endereços","Favoritos","Pagamentos","Notificações","Configurações"].map(x=><button className="flex justify-between rounded-2xl border bg-white p-4 text-left font-bold">{x}<ChevronRight/></button>)}</div></section>}
  </main>:<Dashboard role={role}/>}
  {customer&&<nav className="fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 p-2 md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1"><button onClick={()=>setTab("home")} className="rounded-xl p-2 text-xs font-bold">⌂<br/>Início</button><button onClick={()=>setTab("fairs")} className="rounded-xl p-2 text-xs font-bold">🧺<br/>Feiras</button><button onClick={()=>setTab("orders")} className="rounded-xl p-2 text-xs font-bold">📦<br/>Pedidos</button><button onClick={()=>setTab("profile")} className="rounded-xl p-2 text-xs font-bold">👤<br/>Perfil</button></div></nav>}
  <div className="fixed bottom-20 right-3 z-30 hidden rounded-2xl border bg-white p-2 shadow-lg md:flex gap-1"><button onClick={()=>setRole("customer")} className="text-xs">Cliente</button><button onClick={()=>setRole("vendor")} className="text-xs">Feirante</button><button onClick={()=>setRole("delivery")} className="text-xs">Entregador</button><button onClick={()=>setRole("admin")} className="text-xs">Admin</button></div>
  {cartOpen&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40"><aside className="flex h-full w-full max-w-md flex-col bg-white"><div className="flex justify-between border-b p-5"><div><h2 className="text-xl font-black">Minha Feira</h2><small>{count} item(ns)</small></div><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="flex-1 overflow-auto p-5">{items.length?items.map(p=><div className="mb-3 rounded-2xl border p-3"><div className="flex gap-3"><span className="text-3xl">{p.emoji}</span><div className="flex-1"><b>{p.name}</b><small className="block text-slate-500">{p.vendor}</small><div className="mt-2 flex justify-between"><strong>{money(p.price*cart[p.id])}</strong><span><button onClick={()=>remove(p.id)}><Minus size={15}/></button> {cart[p.id]} <button onClick={()=>add(p.id)}><Plus size={15}/></button></span></div></div><button onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}><Trash2 size={15}/></button></div></div>):<div className="py-20 text-center"><ShoppingBag className="mx-auto text-slate-300" size={45}/><p className="font-bold">Sua sacola está vazia.</p></div>}</div>{items.length>0&&<div className="border-t p-5"><div className="flex justify-between"><span>Subtotal</span><b>{money(total)}</b></div><p className="text-xs text-slate-500">Entrega será calculada no checkout.</p><button className="mt-4 w-full rounded-2xl bg-green-700 py-4 font-black text-white" onClick={()=>alert("Checkout demonstrativo. A integração real será feita na última fase.")}>Continuar para checkout</button></div>}</aside></div>}
 </div>
}
function ProductCard({p,add}:{p:Product;add:(id:number)=>void}){return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex aspect-square items-center justify-center bg-gradient-to-br from-lime-50 to-amber-50 text-6xl">{p.emoji}</div><div className="p-3"><small className="font-bold text-green-700">{p.vendor}</small><h3 className="mt-1 font-black">{p.name}</h3><p className="text-[11px] text-slate-400">{p.fair} · {p.stock} disponíveis</p><div className="mt-3 flex items-center justify-between"><b>{money(p.price)}</b><button onClick={()=>add(p.id)} className="rounded-xl bg-green-700 p-2 text-white"><Plus size={17}/></button></div></div></article>}
function Dashboard({role}:{role:Role}){const data=role==="vendor"?{icon:<Store/>,title:"Painel do feirante",items:["Dashboard","Pedidos","Produtos","Estoque","Minha loja","Minha feira","Vendas","Financeiro","Avaliações","Configurações"]}:role==="delivery"?{icon:<Bike/>,title:"Central de entregas",items:["Dashboard","Entregas disponíveis","Minhas entregas","Mapa e rotas","Ganhos","Histórico","Disponibilidade"]}:{icon:<ShieldCheck/>,title:"Painel administrativo",items:["Dashboard","Usuários","Feiras","Feirantes","Entregadores","Pedidos","Categorias","Financeiro","Relatórios","Moderação"]};return <main className="mx-auto max-w-7xl px-4 py-8"><div className="flex items-center gap-3">{data.icon}<div><small className="font-bold text-green-700">FEIRAÊ</small><h1 className="text-3xl font-black">{data.title}</h1></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{["24 pedidos","R$ 1.842 vendas","8 pendentes","4,9 ★ avaliação"].map(x=><div className="rounded-2xl border bg-white p-5"><b className="text-xl">{x}</b></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.items.map(x=><button className="rounded-2xl border bg-white p-5 text-left shadow-sm"><LayoutDashboard className="text-green-700"/><b className="mt-3 block">{x}</b><small className="text-slate-500">Gerenciar {x.toLowerCase()}</small></button>)}</div></main>}
