-- Historical migration marker: bootstrap_admin_role
-- Already applied to the linked Supabase project before repository migration
-- history was normalized. Intentionally no-op: this file aligns the migration
-- version without replaying production bootstrap/data operations.
